version: "3.8"

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge

services:
  front:
    build:
      context: ./services/front
      dockerfile: ../../cd/docker/front/Dockerfile
      args: {}
    ports:
      - "8080:8080"
    networks:
      - frontend

  rgb-api:
    build:
      context: ./services/api
      dockerfile: ../../cd/docker/api/Dockerfile
      args:
        PYTHON_VERSION: 3.8
        POETRY_VERSION: 1.2.0
    command:
      - "--host=0.0.0.0"
      - "--port=8000"
      - "--log-config=logger.yml"
      - "--reload"
      - "--reload-include"
      - "*.env"
    ports:
      - "8000:8000"
    env_file:
      - ./services/api/envs/docker.env
    volumes:
      - "./services/api/app:/workspace/app" # inject code for live reload
      - "./services/api/envs/docker.env:/workspace/application.env" # inject environment
    networks:
      - frontend
      - backend
